info:
    app:
        desc: Order Service API
        name: order-service
        contact:
           name: Walid ZEDDINI
           email: walid.zeddini@gmail.com
           website: https://www.zeddini.com/
        license: ZPL - ZED GPL GNU  1.2
        license-url: 'https://www.zeddini.com/ZPL-LICENSE-1-2'
        version: 1.0.1
            
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://zipkin-server.ddns.net:9411/zipkin/
# Security configuration
#  security:
#    user:
#      name: zeddini
#      password: zeddini
  # Database
  datasource: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ':::::::::::: Hikari DS NEXIO ORDER-MS POOL ::::::::::::'
      connection-timeout: 60000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ORDER_MS_DB
#    username: zedgres
#    password: zedgres
    url: jdbc:postgresql://ec2-52-54-237-144.compute-1.amazonaws.com:5432/df8gpqtl7fqqdj
    username: qmqirgynylbcpo
    password: 38fc0b6abad6b6b1394dadf3f883e56ef44b296ef54b0c7d67e640309a563dee

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql : false
    properties:
      hibernate:
        format_sql: true
        
# Logger configuration  
logging:
  pattern:
     console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
     file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR

# Eureka Client setting    
eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/  
      
# CF UAA setting  
#uaa:
#  url: ${UAA_URI:http://localhost:8080/uaa}
#  # Client ID on whose behalf the access_token will be verified by Resource Server
#  clientId: uaa-ui-client
#  clientSecret: secret
     
# Keycloak setting       
keycloak:
#  auth-server-url: ${UAA_URI:http://192.168.2.177:8080/auth/}
  auth-server-url: http://key-cloak.ddns.net:8080/auth/
  realm: nexio-api-rest-space
  resource : order
  public-client : false
  bearer-only : true
  credentials : 
    secret : 6de31c9b-3acb-4ae0-a3d5-639bc72c5d29
    use-resource-role-mappings : true  

# Open Feign Client setting
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic

#  Server configuration
server:
  port: 9090 